export const ADMIN_ROUTE = "/admin"
export const AUTHORIZATION_ROUTE = "/authorization"
export const REGISTRATION_ROUTE = "/registration"
export const CART_ROUTE = "/cart"
export const PROFILE_ROUTE = "/profile"
export const SHOP_ROUTE = "/"
export const PRODUCT_ROUTE = "/product"
export const ORDERS_ROUTE = "/orders"